from typing import Protocol

from src.domain.entities import User


class UserRepository(Protocol):
    def get_by_id(self, user_id: str) -> User | None: ...

    def get_by_email(self, email: str) -> User | None: ...

    def create(self, user: User) -> User: ...

    def delete_by_id(self, user_id: str) -> bool: ...
